# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate LibraryCode

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
       file-url: "https://github.com/LiteLDev-LXL/LXLDevHelper-generate/raw/master/Generate.jar"
       file-name: "Generate.jar"
    - name: Run jar
      run: |
        rm -rf Library/*
        java -jar Generate.jar
    - name: ls
      run: ls
    - name: zip
      uses: papeloto/action-zip@v1
      with:
        files: Library
        dest: Library.zip
    - name: Move to folder
      run: |
        rm -rf Generate/*
        mv Library.zip Builds/Library.zip
        mv Library/* Generate
        rm -rf Library

    - name: commit
      run: |
        git config --global user.email 3601594248@qq.com
        git config --global user.name moxicat
        git add *
        git commit -m "update" -a
    - name: Push change
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
