# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate LibraryCode

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
       file-url: "https://github.com/LiteLDev-LXL/LXLDevHelper-generate/raw/master/Generate.jar"
       file-name: "Generate.jar"
    - name: Run jar
      run: java -jar Generate.jar
    - name: ls
      run: ls
